### ISSUE TITLE
String "Connecter" apparently untranslated

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1110]
In the login page the French version of Login always appear.

**Comment by josemvm** [comment]
hi @pcav fixed here https://github.com/3liz/lizmap-web-client/pull/1015

**Comment by pcav** [comment]
Thanks. Still not found in transifex.

Il 18 marzo 2019 13:04:28 CET, "José Macau" <notifications@github.com> ha scritto:
>hi @pcav fixed here https://github.com/3liz/lizmap-web-client/pull/1015
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1110#issuecomment-473882744

-- 
Sorry for being short

**Comment by josemvm** [comment]
it uses an existing string

**Comment by pcav** [comment]
Sorry, I probably miss your point: it is still untranslated in latest published version

**Comment by rldhont** [comment]
@pcav In 3.2.2, the localized string is used but in Italian is still in English https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/var/overloads/jcommunity/locales/it_IT/login.UTF-8.properties#L23

In transifex, the string has been localized, we have to download and update it.

If you still have `Connecter` and not `Sign in`, you have to clean the lizmap temp directory with the script `clean_vartmp.sh`

**Comment by pcav** [comment]
Thanks for the explanation.

**Comment by nboisteault** [comment]
@pcav can the issue be closed ?

**Comment by pcav** [comment]
Yes, thanks
