### ISSUE TITLE
unexpected behaviour with filter data with form and popup

### ISSUE THREAD

**Issue by saeri-ims** [3liz/lizmap-web-client#1417]
### What is the bug?

When clicking on features that have been subset with "filter with form" tool the popup does not show only the filtered features but keeps on showing all the records. Note data are points representing plants, in one location there are more plants sharing the same x and y 

### Steps to reproduce the issue

1. The dataset is coming from postgres and represent point features. In lizmap tool I have set the layer so that can be filtered by species common names using "filter data with form". 
2. Click on 'Filter' in lizmap webclient
3. Type a plant species common name
4. Click on the main map to read the attribute table info from the pop-up
5. The pop-up returns all the plant species names which have the same x,y location. Also those that have not been filtered if i keep at a broad scale. If i zoom in (very very close to the point) then it seems that the popup retrieve only the filtered records.

### Expected behavior
The pop-up should only show the filtered plant species at any zoom level. If i do the same using the attribute table and i search for plant species name, filter the layer and then click on the map, the pop-up shows only the filtered features (at any zoom layer). Hence, i think there is a but with filter by form.

### Screenshots and logs
![plant_filter](https://user-images.githubusercontent.com/42073830/70147734-a439ce00-1683-11ea-82f6-2cbbfdb254a7.png)

![plantspopup](https://user-images.githubusercontent.com/42073830/70147772-b582da80-1683-11ea-83dc-b1af79bc1c8c.png)

### Environment

 - Lizmap version: 3.3
 - QGIS Server version: >= 3.0
 - QGIS Project version: 3.4 LTR
 - OS (Windows, Linux, MacOS, Android…):  Linux Ubuntu 18
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? default

**Comment by rmarzocchi84** [comment]
We encountered the same problem. Maybe it is related to getfeatureinfo request which is different from getmap request?

**Comment by nboisteault** [comment]
@saeri-ims Is it fixed now with LWC 3.3.9 ?

**Comment by rmarzocchi84** [comment]
@nboisteault I will install tomorrow LWC 3.3.8 and I will do some test for you

**Comment by rmarzocchi84** [comment]
@nboisteault  LWC 3.3.8 installed, but the problem it seems to be not fixed.. my colleague @robifag will add soon a GIF to show the problem. probably only the #1446 issue is solved, but we need to test it!

**Comment by RobiFag** [comment]
Hi @nboisteault, here a short gif to show the problem
![info_filter](https://user-images.githubusercontent.com/25825472/86482826-fc889980-bd52-11ea-8f7d-1887bb6d0bc4.gif)

**Comment by nboisteault** [comment]
@rmarzocchi84 @RobiFag Thanks. I'll take a look ASAP.

**Comment by ygorigor** [comment]
For info: this issue is also present in LWC 3.4.

**Comment by nboisteault** [comment]
We need to make a big refactoring of this tool so I change milestone to 4.

**Comment by RobiFag** [comment]
Hi @nboisteault so the filter tool requires a huge refactoring hence will also other issues related to this tool be designed for the 4.0 version? For instance https://github.com/3liz/lizmap-web-client/issues/1674

**Comment by nboisteault** [comment]
Hi @RobiFag probably but i don't know yet.

**Comment by rmarzocchi84** [comment]
For #1674 the solution @RobiFag proposed in the #747 (modifying the filter.js) is close to solution and it is a big upgrade

**Comment by nboisteault** [comment]
@mdouchin When using filter in attribute table execution goes [here](https://github.com/3liz/lizmap-web-client/blob/master/assets/src/legacy/map.js#L3518) and the layer get a `filtertoken` in its vendorParams which is then used for getFeatureInfo requests.

When filtering with the form filter the execution is stopped above. If I comment out [here](https://github.com/3liz/lizmap-web-client/blob/master/assets/src/legacy/map.js#L3480)  and [here](https://github.com/3liz/lizmap-web-client/blob/master/assets/src/legacy/map.js#L3500) the bug is fixed.
