### ISSUE TITLE
Layer field's Edit Widget applied in the form when editing but not when consulting

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#155]
Some of the field in our tables are filled with codes. These codes are described in other tables. Example:
In some tables there is the field status which stores OK,RE,BA for example. 
In another table called statuses we store the traduction of those codes:

OK --> GOOD
RE --> REGULAR 
BA --> BAD

In QGIS, we use the field's edit widget tool (value relation option (we have the other data tables loaded to the workspace) to make the proper traduction for each field:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7833520/ba71eb90-0467-11e5-83a9-40d227ba370f.png)

In QGIS we see the traductions OK:

![sin titulo2](https://cloud.githubusercontent.com/assets/12136796/7833586/31ee4ec0-0468-11e5-83c5-5dd602186e16.png)

But in lizmap, when clickin on an item, the traductions are not displayed:

![sin titulo3](https://cloud.githubusercontent.com/assets/12136796/7833519/ba711846-0467-11e5-8b77-ebf64aaf0cc0.png)

If I activate the edition for the layer, on the other hand, the comboxes (with all possible values), checksboxes and other stuff is being displayed ok.

**Comment by rldhont** [comment]
Hi @jaitor1, which QGIS-Server version do you use ?

**Comment by jaitor1** [comment]
Hi @rldhont  QGIS 2.6.1 Brighton

**Comment by rldhont** [comment]
Can you test it with QGIS 2.8 ? I think this issue has been fixed in QGIS 2.8.

**Comment by jaitor1** [comment]
I updated to QGIS 2.8.2 Wien and the issue still remains:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7934487/45f07faa-0928-11e5-9abe-283a8dcb70f2.png)

**Comment by rldhont** [comment]
OKI, it means it's a feature to develop.

The trick is to use a DB and to create field with the label published in WMS

**Comment by rldhont** [comment]
@jaitor1 does the issue remains with QGIS 2.14 ?

**Comment by nboisteault** [comment]
Hi,
@rldhont the issue remains in QGIS 2.18 in the Lizmap data table.
In my case in 'Espèce' column I should have a the string value and not the id (1736)

![image](https://cloud.githubusercontent.com/assets/2145040/20675463/a716af5e-b58c-11e6-9003-34a253ed2310.png)

**Comment by rldhont** [comment]
What about QGIS 2.14 which is LTR ?

**Comment by nboisteault** [comment]
I updated from QGIS 2.14.8 today, it was not working either.

**Comment by nboisteault** [comment]
This issue is related to https://github.com/3liz/lizmap-web-client/issues/747

**Comment by nboisteault** [comment]
Duplicate of #747
