### ISSUE TITLE
3.7.15 - 3.8.12 - 3.9.5-pre - 3.10.0-pre: Layer sub-group not automatically active/deactive despite corresponding setting (group as Layer) 

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4652]
### What is the bug? (in English)

Grouped layergroups are not displayed correctly in subgroups as active/deactive according to the QGIS themes.

in QGIS:
![image](https://github.com/user-attachments/assets/b42f0486-3f17-46d8-83b5-5de8c886bf34)

in Lizmap:
![image](https://github.com/user-attachments/assets/6414af3d-489b-4c7a-b82d-bb57351505c4)
(see https://cx21-8.webgis.biz/index.php/view/map?repository=buergergis8&project=_buergergis_3_8)

It does not matter whether the group checkboxes are displayed or not.

The error also occurs in 3.7.10-pre from 24/07/2024

### Steps to reproduce the issue

see What is the bug

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0-rc.3
* Lizmap plugin : 4.3.19
* QGIS Desktop : 3.34.9
* QGIS Server : 3.34.9
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.1

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : no
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04 / Win10

### Browsers

Chrome

### Browsers version

Chrome Version 126.0.6478.183

**Comment by Antoviscomi** [comment]
I confirm the anomaly,
QGIS setting
![Schermata del 2024-07-25 11-12-23](https://github.com/user-attachments/assets/8d26a87c-3ea0-492e-9972-b55c22dad5c7)

LWC 3.8-rc3 
![Schermata del 2024-07-25 11-12-59](https://github.com/user-attachments/assets/1e625e44-2186-4a34-8692-45c1a3b534aa)

LWC 3.7.9
![Schermata del 2024-07-25 11-14-57](https://github.com/user-attachments/assets/f14ec4fc-2025-41a3-9aa1-f5e05fe9843e)

**Comment by guenterw** [comment]
Unfortunately, the error still exists in version 3.7.10
Example with the settings from above see 
https://cx21-7.webgis.biz/index.php/view/map?repository=buergergis7&project=Test_Herbolzheim7

**Comment by Antoviscomi** [comment]
@guenterw this bug it seems to br fixed in 3.8.0

**Comment by guenterw** [comment]
@Antoviscomi unfortunately true. I still have the error in 3.8.0 as described above:

QGIS 3.34.10
![image](https://github.com/user-attachments/assets/3875dafe-11a6-4750-8f42-1dda1c2f035b)

In Lizmap 3.8.0
![image](https://github.com/user-attachments/assets/e9ab989c-18bb-406b-b8d6-2e63835e94d7)

**Comment by guenterw** [comment]
The error also exists in the future versions 3.9.0-pre and 3.10.0-pre (both from 24.10.2024)
https://cx21-9.webgis.biz/index.php/view/map?repository=buergergis9&project=bauleitplanung_3_9
https://cx21-10.webgis.biz/index.php/view/map?repository=buergergis9&project=bauleitplanung_3_10
(the “Flächennutzungsplan” group should not be active)

**Comment by meyerlor** [comment]
Is there any news about a possible progress (or a reason why there is none?)
This is the only reason i can not yet switch from 3.6.x versions to the new ones - it would mean a lot of manual work to set up own projects so i can use their WMS to get the desired result. Would happily support the developement financially if this is why it staled!

**Comment by guenterw** [comment]
@Antoviscomi, I test every version in the hope that the bug will be fixed (hence the renaming of the title). 
![image](https://github.com/user-attachments/assets/ee917903-7b9d-4c25-82ff-3c6b86cf940a)
https://cx21-7.webgis.biz/index.php/view/map?repository=buergergis7&project=bauleitplanung_3_7
If this map (Flächennutzungsplan) is displayed, the error still exists. Because this grouped layergroup is deactivated in QGIS (see above). Version 3.7 is particularly important for me, as I can't migrate to 3.8 with many projects because of Ubuntu 20.04.

@meyerlor is right. It's a lot of work. I also see the only possibility in providing my own WMS services for these grouped layergroups.
With the migration of many older projects, this is a huge effort. But it is also necessary for new projects if you work consistently with the QGIS themes and don't want to do without the grouped layergroups.
@meyerlor Thank you for your willingness to support the troubleshooting financially if necessary. At the time, I also financially supported the use of subgroups in the map themes.

**Comment by meyerlor** [comment]
well, since i had some time to look a bit into the code, i figured the problem is in the logic when reading the .qgs project file's xml codeblock:
```
  <visibility-presets>
    <visibility-preset has-expanded-info="1" has-checked-group-info="1" name="Test_Theme">
      <layer id="Welt_03dfe6de_5232_4da8_b553_b0278b501280" style="default" expanded="1" visible="0"/>
      <expanded-legend-nodes id="Welt_03dfe6de_5232_4da8_b553_b0278b501280"/>
      <checked-group-nodes/>
      <expanded-group-nodes>
        <expanded-group-node id="Hallo"/>
      </expanded-group-nodes>
    </visibility-preset>
  </visibility-presets>

```
This is the XML for this setup in QGIS (Theme called "Test_Theme":

![Image](https://github.com/user-attachments/assets/cd7ebb23-0ad2-4505-acfd-29fef4e746ad)

In https://github.com/3liz/lizmap-web-client/blob/b12f66df4b3aac0967a0e8e4a2f7e4de6ab8b577/lizmap/modules/lizmap/classes/qgisProject.class.php#L654-L667

The logic does not really add up:
As soon a layer is not visible, it is ignored by the theme-class
To reflect QGIS behaviour all layers, regardless of their visibility status (which is affected by the parent group) should be returned. And when a layer is in the return array, imho it should be reflected in the Lizmap Legend with a "checked" layer state (but ofc, not visible on the map because the parent group is not checked!)

What do you think @rldhont / @Gustry ?. Any chance to get this done for 3.9/3.10 ? Still my pledge for financing this stands! Any estimate if it's doable or nto would be highly appreciated! Happy to continue our already ongoing (but inactive) mail conversation! :)

**Comment by Antoviscomi** [comment]
@guenterw after @meyerlor fix the behaviour in 3.9.4 and 3.11-pre it seems to respect the qgs settings fixing this issue, can you confirm? If so this issue can be closed

**Comment by meyerlor** [comment]
I would recommend to wait for this PR to be merged:
https://github.com/3liz/lizmap-web-client/pull/6284

In the original PR i overlooked a small thing: when having subgroups checked, they trigger in lizmap again the parent group to be checked as well. This new PR will fix it

**Comment by Antoviscomi** [comment]
@meyerlor I also try to fix by consolidate the layer groups nodes directly in lizmap-web-client/src/classes/Project/Qgis/ProjectVisibilityPreset.php but also in mine the e2e for php 8.4 and  8.2 failed so i deleted the PR 

```
``diff` --git a/lizmap-web-client/src/classes/Project/Qgis/ProjectVisibilityPreset.php b/lizmap-web-client/src/classes/Project/Qgis/ProjectVisibilityPreset.php
index 3c9bd81..81e42b7 100644
--- a/lizmap-web-client/src/classes/Project/Qgis/ProjectVisibilityPreset.php
+++ b/lizmap-web-client/src/classes/Project/Qgis/ProjectVisibilityPreset.php
@@ -63,13 +63,26 @@ class ProjectVisibilityPreset extends BaseQgisObject
 
         $depth = $oXmlReader->depth;
         while ($oXmlReader->read()) {
+
+            // Support both old (<visibility-preset>) and new (<visibilityPreset>) QGIS XML formats
+            $isVisibilityPresetEnd =
+                ($oXmlReader->localName === 'visibility-preset' ||
+                 $oXmlReader->localName === 'visibilityPreset');
+
             if ($oXmlReader->nodeType == \XMLReader::END_ELEMENT
-                && $oXmlReader->localName == 'visibility-preset'
+                && $isVisibilityPresetEnd
                 && $oXmlReader->depth == $depth) {
                 break;
             }
 
             if ($oXmlReader->nodeType != \XMLReader::ELEMENT) {
                 continue;
             }

> @@ -98,7 +111,11 @@ class ProjectVisibilityPreset extends BaseQgisObject

             } elseif ($tagName == 'checked-group-node') {
                 $data['checkedGroupNodes'][] = $oXmlReader->getAttribute('id');
             } elseif ($tagName == 'expanded-group-node') {
                 $data['expandedGroupNodes'][] = $oXmlReader->getAttribute('id');
-            } elseif ($tagName == 'checked-legend-nodes') {
+
+            // Support both <checked-legend-nodes> and <checkedLegendNodes>
+            } elseif ($tagName === 'checked-legend-nodes'
+                  || $tagName === 'checkedLegendNodes') {
+
                 // if the element is empty, skip it
                 if ($oXmlReader->isEmptyElement) {
                     continue;
@@ -110,14 +127,29 @@ class ProjectVisibilityPreset extends BaseQgisObject
                 $legendNodeDepth = $oXmlReader->depth;
                 $legendNodes = array();
 
                 while ($oXmlReader->read()) {
-                    if ($oXmlReader->nodeType == \XMLReader::END_ELEMENT
-                        && $oXmlReader->localName == 'checked-legend-nodes'
-                        && $oXmlReader->depth == $legendNodeDepth) {
-                        break;
-                    }
+                    // Support both end tags
+                    $isLegendNodesEnd =
+                        ($oXmlReader->localName === 'checked-legend-nodes' ||
+                         $oXmlReader->localName === 'checkedLegendNodes');
 
-                    if ($oXmlReader->nodeType == \XMLReader::ELEMENT
-                        && $oXmlReader->localName == 'checked-legend-node') {
-                        $legendNodes[] = $oXmlReader->getAttribute('id');
-                    }
+                    if ($oXmlReader->nodeType == \XMLReader::END_ELEMENT
+                        && $isLegendNodesEnd
+                        && $oXmlReader->depth == $legendNodeDepth) {
+                        break;
+                    }
+
+                    // Support both <checked-legend-node> and <checkedLegendNode>
+                    $isLegendNode =
+                        ($oXmlReader->localName === 'checked-legend-node' ||
+                         $oXmlReader->localName === 'checkedLegendNode');
+
+                    if ($oXmlReader->nodeType == \XMLReader::ELEMENT
+                        && $isLegendNode) {
+                        $legendNodes[] = $oXmlReader->getAttribute('id');
+                    }
                 }
 
                 if (!empty($legendNodes)) {
                     $data['checkedLegendNodes'][$layerId] = `$legendNodes;`
```


My patch was this but I'm not able to successful build it because of the failure of e2e that seem related to a not well understandable users creation issue.  @rldhont maybe a mismatch or issue in e2e recent migration?

**Comment by guenterw** [comment]
> In the original PR i overlooked a small thing: when having subgroups checked, they trigger in lizmap again the parent group to be checked as well. This new PR will fix it

That's right. My original problem still exists. It's due to the sub-sub-groups (activated here).

Thanks for your work, @meyerlor . I hope you can fix it.

in QGIS:
<img width="873" height="250" alt="Image" src="https://github.com/user-attachments/assets/1a30b74d-bc66-4e2a-b633-7a32aa44af25" />

In Lizmap:
<img width="906" height="455" alt="Image" src="https://github.com/user-attachments/assets/19872df3-7b5c-4b5e-983d-a4070d79e962" />

Test with LM 3.9.5-pre (10.12.2025), QGIS 3.40.13
https://cx21-9.webgis.biz/

**Comment by meyerlor** [comment]
yes, this is exactly the problem i fixed with the (still open) PR https://github.com/3liz/lizmap-web-client/pull/6284 :)

What i have not tested though is what happens when you have groups + the lizmap plugin option "group as layer" checked for a group. This is beyond's QGIS themes, so i need to implement it somehow differently.

**Comment by meyerlor** [comment]
you can test it now with 3.9.5-pre, it works, as well with grouped layergroups without further work required :)

**Comment by guenterw** [comment]
Thank you very much, @meyerlor !
After updating to 3.9.5-pre from December 16, 2025 (also 3.10.0-pre), everything works perfectly, even with sub-sub-groups.
When 3.9.5 is public, I will close the issue.
