### ISSUE TITLE
Popups do not work after zoom

### ISSUE THREAD

**Issue by Giofal** [3liz/lizmap-web-client#541]
I noticed the following problem: when the map is loaded for the first time (scale 1: 1,000,000) popups are operating normally.
When I use the zoom (scale 1: 10,000) popups no longer work.
Also returning to the previous zoom popups do not work.

Also in the project Montpellier - Transports when the scale is 1: 2,250 popups at Tram stops will not open more popups.
With the release 3.0.10 this was not the case.
Thanks for your help
A greeting.
Giovanni

qgis 2.18.2 on osx. Ubuntu 16.04 php 7.0

**Comment by josemvm** [comment]
👎 unfortunately...

**Comment by Giofal** [comment]
The last working release is 3.1rc1 discharged on 2017/02/20
A greeting.
Giovanni

**Comment by rldhont** [comment]
I can't reproduce this issue.
What is your popup tolerance ?

**Comment by josemvm** [comment]
hi @rldhont 

on montpellier project try to do a deep zoom by rectangule over Parc du Peyrou zone and after click somewhere on the MONTPELLIER CENTRE. the popup doesn't appear

**Comment by rldhont** [comment]
hi @josemvm tested and the popup appears

**Comment by josemvm** [comment]
with a empty caches:

[zoomByRectangule2.zip](https://github.com/3liz/lizmap-web-client/files/854491/zoomByRectangule2.zip)

**Comment by rldhont** [comment]
@josemvm and @Giofal 
how did you zoom ?
Did you use the Plus button ?
Did you use the zoom by rectangle button ?
Didi you use the Maj keyboard shortcut ?

**Comment by josemvm** [comment]
zoom by rectangle button

**Comment by josemvm** [comment]
in fact, thw ehavior is different depending on the zoom way

**Comment by josemvm** [comment]
the popup stop after using the zoom by rectangule button!

**Comment by rldhont** [comment]
In master and 3.0.12, I can't reproduce the issue

**Comment by Giofal** [comment]
Hi,
the problem is only in 3.1.
g.

**Comment by josemvm** [comment]
weird... i'm testing with these last 2 versions and also confirmed this point:

> The last working release is 3.1rc1 discharged on 2017/02/20
A greeting.
Giovanni

**Comment by Giofal** [comment]
My two cents…:)
g.

https://www.dropbox.com/s/frlqzecbekcfagx/2017-03-20%2013-42-02.zip?dl=0

**Comment by rldhont** [comment]
Fixed in 3.0 branch

**Comment by josemvm** [comment]
thanks @rldhont
:-)

**Comment by Giofal** [comment]
I edit the line in file lizmap/www/js/map.js in my release 3.1 but the bug remains… :(
thanks anyway
g

**Comment by josemvm** [comment]
after emptying the caches, it will work well
